/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT DIRECTLY!
 * 
 * Edit the original stylesheet at:
 * libs/ui/components/banana/src/lib/banana.style.css
 */

export const style = `.lib-banana{background-color:#d3d3d3}`