/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT DIRECTLY!
 * 
 * Edit the original stylesheet at:
 * libs/ui/components/button/src/lib/button.style.css
 */

export const style = `.lib-button{background:var(--theme-color-button-primary);border-radius:.25rem;color:#fff;padding:.5rem 1.5rem;min-width:8rem;cursor:pointer;text-transform:uppercase}.lib-button:hover{background:var(--theme-color-button-primary-hover)}.lib-button--type-secondary{background:var(--theme-color-button-secondary)}.lib-button--type-secondary:hover{background:var(--theme-color-button-secondary-hover)}.lib-button--width-tight{min-width:0;padding:.5rem 1rem}.lib-button--width-full{width:100%}`