/**
* DO NOT EDIT THIS FILE DIRECTLY
* THIS FILE IS AUTOMATICALLY GENERATED AT BUILD
* 
* Edit the stylesheet at:
* libs/ui/components/input/src/lib/input.style.css
*/

export const style = /* css */ `
.lib-input {
  border: solid 2px green;
}
`