/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT DIRECTLY!
 * 
 * Edit the original stylesheet at:
 * libs/ui/components/input/src/lib/input.style.css
 */

export const style = /* css */ `
.lib-input {
  border: solid 2px red;
}
`