
/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT DIRECTLY!
 *
 * Edit the original stylesheet at:
 * libs/ui/components/input/src/lib/input.style.css
 */

export const style = `.lib-input{border:solid 1px #929292;width:200px;border-radius:.25rem;padding:.35rem .45rem}.lib-input:focus{outline:0;box-shadow:0 0 0 1px #929292}.lib-input::placeholder{opacity:.4}.lib-input--small{width:150px}.lib-input--full{width:100%}`
    