/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT DIRECTLY!
 * 
 * Edit the original stylesheet at:
 * libs/ui/components/card/src/lib/card.style.css
 */

export const style = `.lib-card{box-shadow:rgba(99,99,99,.2) 0 2px 8px 0;padding:2rem;border-radius:1rem}`